fix(ci): makes attic push failures non build breaking

diff --git a/.github/workflows/build-and-cache-flake.yml b/.github/workflows/build-and-cache-flake.yml
--- a/.github/workflows/build-and-cache-flake.yml
+++ b/.github/workflows/build-and-cache-flake.yml
@@ -55,7 +55,8 @@ jobs:
           RESULT=$(jq -r '.[0].outputs | to_entries[] | select(.key == "out").value' build-result-${{ matrix.host }}.json)
           if [ -n "$RESULT" ]; then
             echo "Pushing $RESULT to Attic..."
-            attic push "${{ secrets.ATTIC_CACHE }}" "$RESULT"
+            attic push "${{ secrets.ATTIC_CACHE }}" "$RESULT" \
+              || echo "[WARNING] Failed to push (parts of) '$RESULT' to Attic, but build succeeded."
           else
             echo "No output found in build result"
             exit 1
